const response = {
  "ResultSet": {
    "status": 0,
    "errors": "success",
    "success": true,
    "totalPages": 0,
    "totalResultsAvailable": 1,
    "currentPage": 0,
    "recordNumber": 1,
    "pageLines": 20,
    "metadata": {},
    "Result": [
      {
        "processId": 232,
        "processTypeId": 93,
        "departmentId": 0,
        "includeDepartmentId": 0,
        "createEmployeeId": 0,
        "processName": "预算单变更",
        "countersign": false,
        "holdDepartmentId": 0,
        "holdDutyId": 0,
        "enable": true,
        "detailSystemProcessActivity": [
          {
            "processActivityId": 2968,
            "processId": 232,
            "activityType": 3,
            "activityName": "宋",
            "activitySerialNo": 3,
            "posx": 682,
            "posy": 111,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 3541,
            "departmentId": 0,
            "roleId": 0,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 2983,
            "processId": 232,
            "activityType": 0,
            "activitySerialNo": 0,
            "posx": 106,
            "posy": 290,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 0,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 2988,
            "processId": 232,
            "activityType": 1,
            "activitySerialNo": 999,
            "posx": 1608,
            "posy": 221,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 0,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3027,
            "processId": 232,
            "activityType": 2,
            "activityName": "部门负责人",
            "activitySerialNo": 4,
            "posx": 440,
            "posy": 307,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 59,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3028,
            "processId": 232,
            "activityType": 2,
            "activityName": "部门分管领导",
            "activitySerialNo": 5,
            "posx": 670,
            "posy": 304,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 127,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3029,
            "processId": 232,
            "activityType": 3,
            "activityName": "财务经理",
            "activitySerialNo": 6,
            "posx": 846,
            "posy": 309,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 10,
            "roleId": 23,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3030,
            "processId": 232,
            "activityType": 3,
            "activityName": "财务总监",
            "activitySerialNo": 7,
            "posx": 1067,
            "posy": 312,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 10,
            "roleId": 21,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3045,
            "processId": 232,
            "activityType": 2,
            "activityName": "运营中心",
            "activitySerialNo": 8,
            "posx": 1123,
            "posy": 471,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 539,
            "departmentId": 0,
            "roleId": 0,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 1,
            "executeName": ""
          },
          {
            "processActivityId": 3046,
            "processId": 232,
            "activityType": 2,
            "activityName": "营销总监",
            "activitySerialNo": 9,
            "posx": 432,
            "posy": 469,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 78,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3047,
            "processId": 232,
            "activityType": 2,
            "activityName": "营销中心负责人",
            "activitySerialNo": 10,
            "posx": 636,
            "posy": 473,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 3,
            "departmentId": 0,
            "roleId": 0,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3048,
            "processId": 232,
            "activityType": 2,
            "activityName": "陈总",
            "activitySerialNo": 11,
            "posx": 1277,
            "posy": 443,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 2832,
            "departmentId": 0,
            "roleId": 0,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 1,
            "executeName": ""
          },
          {
            "processActivityId": 3049,
            "processId": 232,
            "activityType": 2,
            "activityName": "财务经理",
            "activitySerialNo": 12,
            "posx": 1438,
            "posy": 410,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 10,
            "roleId": 23,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3050,
            "processId": 232,
            "activityType": 2,
            "activityName": "部门负责人",
            "activitySerialNo": 13,
            "posx": 440,
            "posy": 634,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 31,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          },
          {
            "processActivityId": 3051,
            "processId": 232,
            "activityType": 2,
            "activityName": "部门主管领导",
            "activitySerialNo": 14,
            "posx": 626,
            "posy": 642,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 61,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 1,
            "executeName": ""
          },
          {
            "processActivityId": 3052,
            "processId": 232,
            "activityType": 2,
            "activityName": "部门分管领导",
            "activitySerialNo": 15,
            "posx": 819,
            "posy": 643,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 60,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 1,
            "executeName": ""
          },
          {
            "processActivityId": 3053,
            "processId": 232,
            "activityType": 2,
            "activityName": "大项目经理",
            "activitySerialNo": 16,
            "posx": 970,
            "posy": 646,
            "timeOutAction": 0,
            "executorType": 0,
            "employeeId": 0,
            "departmentId": 0,
            "roleId": 80,
            "ifAllowOver": false,
            "isEnable": true,
            "poolType": 0,
            "executeName": ""
          }
        ],
        "detailSystemProcessLink": [
          {
            "processLinkId": 3280,
            "processId": 232,
            "condition": "预算类型='外包预算' and 外包类型='公司外包'",
            "processActivityId": 0,
            "toProcessActivityId": 9
          },
          {
            "processLinkId": 3281,
            "processId": 232,
            "processActivityId": 9,
            "toProcessActivityId": 10
          },
          {
            "processLinkId": 3282,
            "processId": 232,
            "processActivityId": 10,
            "toProcessActivityId": 8
          },
          {
            "processLinkId": 3185,
            "processId": 232,
            "processActivityId": 3,
            "toProcessActivityId": 999
          },
          {
            "processLinkId": 3250,
            "processId": 232,
            "processActivityId": 0,
            "toProcessActivityId": 3
          },
          {
            "processLinkId": 3258,
            "processId": 232,
            "condition": "预算类型='部门预算'",
            "processActivityId": 0,
            "toProcessActivityId": 4
          },
          {
            "processLinkId": 3259,
            "processId": 232,
            "processActivityId": 4,
            "toProcessActivityId": 5
          },
          {
            "processLinkId": 3260,
            "processId": 232,
            "processActivityId": 5,
            "toProcessActivityId": 6
          },
          {
            "processLinkId": 3261,
            "processId": 232,
            "processActivityId": 6,
            "toProcessActivityId": 7
          },
          {
            "processLinkId": 3262,
            "processId": 232,
            "processActivityId": 7,
            "toProcessActivityId": 999
          },
          {
            "processLinkId": 3283,
            "processId": 232,
            "processActivityId": 8,
            "toProcessActivityId": 11
          },
          {
            "processLinkId": 3284,
            "processId": 232,
            "processActivityId": 11,
            "toProcessActivityId": 12
          },
          {
            "processLinkId": 3285,
            "processId": 232,
            "processActivityId": 12,
            "toProcessActivityId": 999
          },
          {
            "processLinkId": 3286,
            "processId": 232,
            "condition": "预算类型= '外包预算' and 外包类型 = '项目外包'",
            "processActivityId": 0,
            "toProcessActivityId": 13
          },
          {
            "processLinkId": 3287,
            "processId": 232,
            "processActivityId": 13,
            "toProcessActivityId": 14
          },
          {
            "processLinkId": 3288,
            "processId": 232,
            "processActivityId": 14,
            "toProcessActivityId": 15
          },
          {
            "processLinkId": 3289,
            "processId": 232,
            "processActivityId": 15,
            "toProcessActivityId": 16
          },
          {
            "processLinkId": 3290,
            "processId": 232,
            "processActivityId": 16,
            "toProcessActivityId": 8
          }
        ]
      }
    ]
  }
}

export default response